export type DemoLocale = "zh-Hans" | "en" | "ja";

const english: Record<string, string> = {
  "交互式演示": "Interactive Preview",
  "IB · IGCSE 学习规划": "IB · IGCSE study planning",
  "把 Deadline 变成清晰的行动。": "Turn every deadline into a clear next step.",
  "这是基于真实 SwiftUI 项目制作的浏览器演示。任务与外观设置只保存在当前浏览器。":
    "This browser demo mirrors the real SwiftUI app. Tasks and appearance settings stay in this browser.",
  "交互数据已启用": "Interactive data enabled",
  "重置演示": "Reset demo",
  "重播介绍": "Replay intro",
  "语言": "Language",
  "简体中文": "Simplified Chinese",
  "英语": "English",
  "日语": "Japanese",
  "欢迎使用": "Welcome to",
  "学习规划，简单清晰。": "Study planning, simple and clear.",
  "欢迎使用 Planora": "Welcome to Planora",
  "一款为 IB 和 IGCSE 学生设计的学习规划工具。先选择课程体系与科目，再清晰查看任务、进度和重要日期。":
    "A study planner for IB and IGCSE students. Choose your curriculum and subjects, then see tasks, progress, and important dates clearly.",
  "管理课程": "Organize courses",
  "按课程体系整理科目与学习内容。": "Keep subjects and learning content organized by curriculum.",
  "掌握节点": "Track milestones",
  "把作业、考试和长期项目放进清晰时间线。":
    "Place assignments, exams, and long projects on one clear timeline.",
  "推进进度": "Move work forward",
  "用百分比或阶段追踪每一项学习任务。":
    "Track every learning task with percentages or project stages.",
  "开始使用": "Get Started",
  "首页": "Home",
  "任务": "Tasks",
  "搜索": "Search",
  "我的": "Me",
  "新建": "New",
  "主导航": "Main navigation",
  "新建任务": "New Task",
  "关闭": "Close",
  "返回": "Back",
  "今天": "Today",
  "执行今天的计划": "Follow today's plan",
  "本周": "This Week",
  "查看七天负载": "View the next seven days",
  "当前重点": "Current Focus",
  "完成下一个阶段目标": "Complete the next milestone.",
  "已过日期。查看这个作业。": "This task is overdue. Review it now.",
  "即将到来的任务": "Upcoming Tasks",
  "学习进度": "Learning Progress",
  "本周完成": "Completed This Week",
  "未来七天": "Next Seven Days",
  "日历预览": "Calendar Preview",
  "还没有任务": "No Tasks Yet",
  "点击加号创建第一个学习任务。": "Tap + to create your first learning task.",
  "暂无": "None",
  "项": "items",
  "根据设置显示和排序任务。": "Display and sort tasks using your settings.",
  "重新打开任务": "Reopen task",
  "完成任务": "Complete task",
  "快速查找任务、活动和重要日期。":
    "Quickly find tasks, activities, and important dates.",
  "清除搜索并收起键盘": "Clear search and dismiss keyboard",
  "科目": "Subject",
  "任务类型": "Task Type",
  "状态": "Status",
  "进行中": "In Progress",
  "已完成": "Completed",
  "搜索结果": "Search Results",
  "所有项目": "All Items",
  "没有匹配项目": "No Matching Items",
  "试试其他关键词或筛选条件。": "Try another keyword or filter.",
  "学习空间": "Learning Space",
  "设置": "Settings",
  "外观": "Appearance",
  "任务显示": "Task Display",
  "舒适": "Comfortable",
  "紧凑": "Compact",
  "任务存储": "Task Storage",
  "浏览器本地演示": "Browser-local demo",
  "恢复演示": "Restore Demo",
  "当前科目": "Current Subjects",
  "选择颜色主题与显示模式。": "Choose a color theme and display mode.",
  "颜色主题": "Color Theme",
  "显示模式": "Display Mode",
  "浅色": "Light",
  "深色": "Dark",
  "控制任务列表的外观与排序。": "Control task-list appearance and sorting.",
  "列表密度": "List Density",
  "排序": "Sort",
  "智能排序": "Smart Sort",
  "截止日期": "Deadline",
  "优先级": "Priority",
  "标题": "Title",
  "内容": "Content",
  "显示已完成任务": "Show Completed Tasks",
  "显示进度百分比": "Show Progress Percentage",
  "显示备注": "Show Notes",
  "任务详情": "Task Details",
  "类型": "Type",
  "计划完成": "Planned Date",
  "未安排": "Not Planned",
  "提醒": "Reminders",
  "提前 1 天 · 当天": "1 day before · On the day",
  "进度": "Progress",
  "完成度": "Completion",
  "备注": "Notes",
  "暂无备注": "No notes",
  "标记为已完成": "Mark as Completed",
  "今天没有安排": "Nothing Planned Today",
  "逾期": "Overdue",
  "今天截止": "Due Today",
  "计划今天完成": "Planned for Today",
  "本周还没有安排": "Nothing planned this week",
  "无安排": "No tasks",
  "未安排任务": "Unscheduled",
  "快速新建": "Quick Create",
  "只填写标题、科目和日期。": "Just add a title, subject, and date.",
  "任务名称": "Task name",
  "日期": "Date",
  "计划完成日期": "Planned Date",
  "进度方式": "Progress Style",
  "百分比": "Percentage",
  "阶段": "Stage",
  "重复任务": "Repeating Task",
  "保存任务": "Save Task",
  "作业": "Assignment",
  "实践": "Practical",
  "复习": "Revision",
  "考试": "Exam",
  "活动": "Event",
  "自定义": "Custom",
  "准备": "Preparation",
  "第一轮": "First Round",
  "研究问题": "Research Question",
  "研究": "Research",
  "提纲": "Outline",
  "反思": "Reflection",
  "复习中": "Revising",
  "待参加": "Upcoming",
  "阅读中": "Reading",
  "低": "Low",
  "中": "Medium",
  "高": "High",
  "经典": "Classic",
  "海洋": "Ocean",
  "森林": "Forest",
  "日落": "Sunset",
  "无截止日期": "No Deadline",
  "Outline ready": "Outline ready",
  "整理实验数据，补做异常值并开始绘制图表。":
    "Organize experiment data, repeat anomalies, and start charting.",
  "完成第 7 章导数应用题。": "Complete the Chapter 7 derivative problems.",
  "确认三个物件与 prompt 的联系。":
    "Confirm how the three objects connect to the prompt.",
  "阅读两篇文章并记录新词。":
    "Read two articles and record new vocabulary.",
  "完成摄影活动反思。": "Finish the photography activity reflection.",
};

const japanese: Record<string, string> = {
  "交互式演示": "インタラクティブプレビュー",
  "IB · IGCSE 学习规划": "IB・IGCSE 学習プラン",
  "把 Deadline 变成清晰的行动。": "締切を、明確な次の行動へ。",
  "这是基于真实 SwiftUI 项目制作的浏览器演示。任务与外观设置只保存在当前浏览器。":
    "実際の SwiftUI アプリをもとにしたブラウザ版です。タスクと外観設定はこのブラウザ内だけに保存されます。",
  "交互数据已启用": "インタラクティブデータ有効",
  "重置演示": "デモをリセット",
  "重播介绍": "紹介を再表示",
  "语言": "言語",
  "简体中文": "簡体字中国語",
  "英语": "英語",
  "日语": "日本語",
  "欢迎使用": "ようこそ",
  "学习规划，简单清晰。": "学習計画を、シンプルで明確に。",
  "欢迎使用 Planora": "Planora へようこそ",
  "一款为 IB 和 IGCSE 学生设计的学习规划工具。先选择课程体系与科目，再清晰查看任务、进度和重要日期。":
    "IB・IGCSE 学生向けの学習プランナーです。カリキュラムと科目を選び、タスク・進捗・重要日程を明確に確認できます。",
  "管理课程": "科目を整理",
  "按课程体系整理科目与学习内容。": "カリキュラム別に科目と学習内容を整理します。",
  "掌握节点": "節目を把握",
  "把作业、考试和长期项目放进清晰时间线。":
    "課題・試験・長期プロジェクトを一つの時間軸で管理します。",
  "推进进度": "進捗を前へ",
  "用百分比或阶段追踪每一项学习任务。":
    "パーセントまたは段階で学習タスクを追跡します。",
  "开始使用": "はじめる",
  "首页": "ホーム",
  "任务": "タスク",
  "搜索": "検索",
  "我的": "マイページ",
  "新建": "新規",
  "主导航": "メインナビゲーション",
  "新建任务": "新規タスク",
  "关闭": "閉じる",
  "返回": "戻る",
  "今天": "今日",
  "执行今天的计划": "今日の計画を実行",
  "本周": "今週",
  "查看七天负载": "7日間の負荷を確認",
  "当前重点": "現在の重点",
  "完成下一个阶段目标": "次のマイルストーンを完了しましょう。",
  "已过日期。查看这个作业。": "期限を過ぎています。内容を確認してください。",
  "即将到来的任务": "今後のタスク",
  "学习进度": "学習進捗",
  "本周完成": "今週の完了",
  "未来七天": "今後7日間",
  "日历预览": "カレンダープレビュー",
  "还没有任务": "タスクはまだありません",
  "点击加号创建第一个学习任务。": "＋を押して最初の学習タスクを作成します。",
  "暂无": "なし",
  "项": "件",
  "根据设置显示和排序任务。": "設定に従ってタスクを表示・並べ替えます。",
  "重新打开任务": "タスクを再開",
  "完成任务": "タスクを完了",
  "快速查找任务、活动和重要日期。": "タスク・イベント・重要日をすばやく検索します。",
  "清除搜索并收起键盘": "検索を消去してキーボードを閉じる",
  "科目": "科目",
  "任务类型": "タスク種類",
  "状态": "状態",
  "进行中": "進行中",
  "已完成": "完了",
  "搜索结果": "検索結果",
  "所有项目": "すべての項目",
  "没有匹配项目": "一致する項目はありません",
  "试试其他关键词或筛选条件。": "別のキーワードや絞り込みをお試しください。",
  "学习空间": "学習スペース",
  "设置": "設定",
  "外观": "外観",
  "任务显示": "タスク表示",
  "舒适": "ゆったり",
  "紧凑": "コンパクト",
  "任务存储": "タスク保存",
  "浏览器本地演示": "ブラウザ内デモ",
  "恢复演示": "デモを復元",
  "当前科目": "現在の科目",
  "选择颜色主题与显示模式。": "カラーテーマと表示モードを選択します。",
  "颜色主题": "カラーテーマ",
  "显示模式": "表示モード",
  "浅色": "ライト",
  "深色": "ダーク",
  "控制任务列表的外观与排序。": "タスクリストの外観と並び順を調整します。",
  "列表密度": "リスト密度",
  "排序": "並べ替え",
  "智能排序": "スマート順",
  "截止日期": "締切",
  "优先级": "優先度",
  "标题": "タイトル",
  "内容": "内容",
  "显示已完成任务": "完了タスクを表示",
  "显示进度百分比": "進捗率を表示",
  "显示备注": "メモを表示",
  "任务详情": "タスク詳細",
  "类型": "種類",
  "计划完成": "予定日",
  "未安排": "未設定",
  "提醒": "通知",
  "提前 1 天 · 当天": "1日前・当日",
  "进度": "進捗",
  "完成度": "完了度",
  "备注": "メモ",
  "暂无备注": "メモなし",
  "标记为已完成": "完了にする",
  "今天没有安排": "今日の予定はありません",
  "逾期": "期限切れ",
  "今天截止": "本日締切",
  "计划今天完成": "今日の予定",
  "本周还没有安排": "今週の予定はありません",
  "无安排": "予定なし",
  "未安排任务": "未設定",
  "快速新建": "クイック作成",
  "只填写标题、科目和日期。": "タイトル・科目・日付だけで作成します。",
  "任务名称": "タスク名",
  "日期": "日付",
  "计划完成日期": "予定日",
  "进度方式": "進捗方式",
  "百分比": "パーセント",
  "阶段": "段階",
  "重复任务": "繰り返しタスク",
  "保存任务": "タスクを保存",
  "作业": "課題",
  "实践": "実習",
  "复习": "復習",
  "考试": "試験",
  "活动": "イベント",
  "自定义": "カスタム",
  "准备": "準備",
  "第一轮": "第1ラウンド",
  "研究问题": "研究課題",
  "研究": "研究",
  "提纲": "アウトライン",
  "反思": "振り返り",
  "复习中": "復習中",
  "待参加": "参加予定",
  "阅读中": "読書中",
  "低": "低",
  "中": "中",
  "高": "高",
  "经典": "クラシック",
  "海洋": "オーシャン",
  "森林": "フォレスト",
  "日落": "サンセット",
  "无截止日期": "締切なし",
  "Outline ready": "アウトライン完成",
  "整理实验数据，补做异常值并开始绘制图表。":
    "実験データを整理し、異常値を再測定してグラフ作成を始めます。",
  "完成第 7 章导数应用题。": "第7章の微分応用問題を完了します。",
  "确认三个物件与 prompt 的联系。":
    "3つのオブジェクトとプロンプトの関係を確認します。",
  "阅读两篇文章并记录新词。": "記事を2本読み、新しい語彙を記録します。",
  "完成摄影活动反思。": "写真活動の振り返りを完了します。",
};

export const demoLocales: DemoLocale[] = ["zh-Hans", "en", "ja"];

export function localeLabel(locale: DemoLocale, displayLocale: DemoLocale) {
  const source =
    locale === "zh-Hans" ? "简体中文" : locale === "en" ? "英语" : "日语";
  return copy(displayLocale, source);
}

export function localeCode(locale: DemoLocale) {
  return locale === "zh-Hans" ? "中" : locale === "en" ? "EN" : "日";
}

export function dateLocale(locale: DemoLocale) {
  return locale === "zh-Hans" ? "zh-CN" : locale === "ja" ? "ja-JP" : "en-US";
}

export function copy(locale: DemoLocale, source: string) {
  if (locale === "en") return english[source] ?? source;
  if (locale === "ja") return japanese[source] ?? source;
  return source;
}

export function browserLocale(value?: string): DemoLocale {
  const normalized = value?.toLowerCase() ?? "";
  if (normalized.startsWith("ja")) return "ja";
  if (normalized.startsWith("en")) return "en";
  return "zh-Hans";
}
